### ISSUE TITLE
Running TASER with a mocha test suite

### ISSUE THREAD

**Issue by thepalbi** [cs-au-dk/taser#4]
Hi TASER team!
I read your paper, really cool! I'm interested in trying to replicate running TASER with a mocha test suite (or some other javascript test suite as mentioned in the paper). 

My current setup works just fine for the `example.js` shipped in this repo, but when I try to run it with a simple javascript project having nothing other than an empty test:

```javascript
describe('Missing assertions', function() {
    it('cloneDeep directly from require', function() {

    })
})
```

And running it instrumenting the mocha executable which lives normally under `node_modules/mocha/bin/mocha`, with the following:
```bash
TASER_ROOT="..."
POLICY_FILE="$TASER_ROOT/src/DefaultPolicy.js" \
POLICY_OUT="model.json" \
LIBRARY_UNDER_TEST="lodash" \
bash -c "$TASER_ROOT/instrumented-node/node node_modules/mocha/bin/mocha"
```

I keep getting the following error:

```
Marked sink RegExp
Marked sink match
Marked sink search
Successfully loaded policy: /Users/thepalbi/Facultad/tesis/workspace/taser/src/DefaultPolicy.js
Successfully setup the analysis
`

  Missing assertions
    ✓ cloneDeep directly from require

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 12
        at com.oracle.truffle.object.CoreLocations$LongArrayLocation.getOffset(CoreLocations.java:567)
        at com.oracle.truffle.object.CoreLocations$LongArrayLocation.setLongInternal(CoreLocations.java:525)
        at com.oracle.truffle.object.CoreLocations$LongArrayLocation.setLong(CoreLocations.java:531)
        at com.oracle.truffle.object.CoreLocations$PrimitiveLocationDecorator.setLongInternal(CoreLocations.java:711)
        at com.oracle.truffle.object.CoreLocations$DoubleLocationDecorator.setDouble(CoreLocations.java:818)
[...]
at com.oracle.truffle.js.nodes.instrumentation.DeclareTagProvider$MaterializedFunctionBodyNode.execute(DeclareTagProvider.java:155)
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:84)
        at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:99)
        at com.oracle.truffle.js.runtime.builtins.JSFunction.call(JSFunction.java:311)
        at com.oracle.truffle.js.runtime.JSRuntime.call(JSRuntime.java:2493)
        at com.oracle.truffle.trufflenode.GraalJSAccess.functionCall(GraalJSAccess.java:1424)
        at com.oracle.truffle.trufflenode.GraalJSAccess.functionCall0(GraalJSAccess.java:1433)
Caused by: Attached Guest Language Frames (8)
```

I'm guessing my stacktrace doesn't help much, but wanted to ask if there was something special you did when running TASER alongside with javascript test suites? Almost certain that error occurs because of the instrumented NodeJS vm running the tests framework.

**Comment by thepalbi** [comment]
Just to be sure, I corroborated if this was caused by the JVM I was using. I tried with:
- AdoptJDK 8
- [Graal's latest release](https://github.com/graalvm/graal-jvmci-8/releases/tag/jvmci-21.1-b04)

Still facing the same issue 😞

**Comment by thepalbi** [comment]
Also tried figuring out if the issue is with something in the TASER source code, or Nodeprof.js, and I could replicate the issue without TASER in the middle:

Running Nodeprof.js Jalangi with an empty analysis:
```
mx -v jalangi 
  --analysis /persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/src/ch.usi.inf.nodeprof/js/analysis/trivial/emptyTemplate.js 
  /persistent2/tsm-setup/dynamic-js-codeql/examples/missing-requires/node_modules/mocha/bin/mocha 
    /persistent2/tsm-setup/dynamic-js-codeql/examples/missing-requires/test
```

I found the same error stacktrace:
```
Setting environment variable NODE_JVM_CLASSPATH=/persistent2/tsm-setup/workspace-nodeprof/graal/sdk/mxbuild/dists/jdk1.8/graal-sdk.jar:/persistent2/tsm-setup/workspace-nodeprof/graal/truffle/mxbuild/dists/jdk1.8/truffle-api.jar:/persistent2/tsm-setup/workspace-nodeprof/graal/regex/mxbuild/dists/jdk1.8/tregex.jar:/home/pbalbi/.mx/cache/ICU4J_2e159807158095566726600534034030dddab6d0/icu4j.jar:/persistent2/tsm-setup/workspace-nodeprof/graaljs/graal-js/mxbuild/dists/jdk1.8/graaljs.jar:/persistent2/tsm-setup/workspace-nodeprof/graal/sdk/mxbuild/dists/jdk1.8/launcher-common.jar:/persistent2/tsm-setup/workspace-nodeprof/graaljs/graal-nodejs/mxbuild/dists/jdk1.8/trufflenode.jar:/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/build/nodeprof.jar
env MX__SUITEMODEL=sibling LAUNCHER_COMMON_JAR_PATH=/persistent2/tsm-setup/workspace-nodeprof/graal/sdk/mxbuild/dists/jdk1.8/launcher-common.jar NODE_JVM_CLASSPATH=/persistent2/tsm-setup/workspace-nodeprof/graal/sdk/mxbuild/dists/jdk1.8/graal-sdk.jar:/persistent2/tsm-setup/workspace-nodeprof/graal/truffle/mxbuild/dists/jdk1.8/truffle-api.jar:/persistent2/tsm-setup/workspace-nodeprof/graal/regex/mxbuild/dists/jdk1.8/tregex.jar:/home/pbalbi/.mx/cache/ICU4J_2e159807158095566726600534034030dddab6d0/icu4j.jar:/persistent2/tsm-setup/workspace-nodeprof/graaljs/graal-js/mxbuild/dists/jdk1.8/graaljs.jar:/persistent2/tsm-setup/workspace-nodeprof/graal/sdk/mxbuild/dists/jdk1.8/launcher-common.jar:/persistent2/tsm-setup/workspace-nodeprof/graaljs/graal-nodejs/mxbuild/dists/jdk1.8/trufflenode.jar:/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/build/nodeprof.jar MX_HOME=/persistent2/tsm-setup/mx TRUFFLENODE_JAR_PATH=/persistent2/tsm-setup/workspace-nodeprof/graaljs/graal-nodejs/mxbuild/dists/jdk1.8/trufflenode.jar MX_PRIMARY_SUITE_PATH=/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js MX_SUBPROCESS_COMMAND_FILE=/tmp/mx_subprocess_command.5RDDKr \
/persistent2/tsm-setup/workspace-nodeprof/graaljs/graal-nodejs/out/Release/node --jvm --vm.ea --experimental-options --engine.InstrumentExceptionsAreThrown=true --nodeprof --nodeprof.Analysis=NodeProfJalangi --nodeprof.Scope=module --nodeprof.ExcludeSource=/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/src/ch.usi.inf.nodeprof/js/analysis/trivial/emptyTemplate.js /persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/src/ch.usi.inf.nodeprof/js/jalangi.js --analysis /persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/src/ch.usi.inf.nodeprof/js/analysis/trivial/emptyTemplate.js /persistent2/tsm-setup/dynamic-js-codeql/examples/missing-requires/node_modules/mocha/bin/mocha /persistent2/tsm-setup/dynamic-js-codeql/examples/missing-requires/test
[w] Could not find <return> slot
[w] Could not find <return> slot


  Missing assertions
    ✓ cloneDeep directly from require (504ms)

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 12
	at com.oracle.truffle.object.CoreLocations$LongArrayLocation.getOffset(CoreLocations.java:567)
	at com.oracle.truffle.object.CoreLocations$LongArrayLocation.setLongInternal(CoreLocations.java:525)
	at com.oracle.truffle.object.CoreLocations$LongArrayLocation.setLong(CoreLocations.java:531)
	at com.oracle.truffle.object.CoreLocations$PrimitiveLocationDecorator.setLongInternal(CoreLocations.java:711)
	at com.oracle.truffle.object.CoreLocations$DoubleLocationDecorator.setDouble(CoreLocations.java:818)
	at com.oracle.truffle.object.CoreLocations$DoubleLocationDecorator.setInternal(CoreLocations.java:824)
	at com.oracle.truffle.object.DynamicObjectLibraryImpl$Move.performSet(DynamicObjectLibraryImpl.java:499)

[...]

	at com.oracle.truffle.js.runtime.builtins.JSFunction.call(JSFunction.java:311)
	at com.oracle.truffle.js.runtime.JSRuntime.call(JSRuntime.java:2493)
	at com.oracle.truffle.trufflenode.GraalJSAccess.functionCall(GraalJSAccess.java:1424)
	at com.oracle.truffle.trufflenode.GraalJSAccess.functionCall0(GraalJSAccess.java:1433)
Caused by: Attached Guest Language Frames (8)
[exit code: 1]
  File "/persistent2/tsm-setup/mx/mx.py", line 17428, in <module>
    main()
  File "/persistent2/tsm-setup/mx/mx.py", line 17409, in main
    retcode = c(command_args)
  File "/persistent2/tsm-setup/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/mx.nodeprof/mx_nodeprof.py", line 219, in runJalangi
    _runJalangi(jalangiArgs, outFile=outFile, svm=parsed.svm, debug=parsed.debug, trace=(tracable and parsed.trace));
  File "/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/mx.nodeprof/mx_nodeprof.py", line 60, in _runJalangi
    ret = mx.run(cmdArgs, nonZeroIsFatal=True, out=out);
  File "/persistent2/tsm-setup/mx/mx.py", line 12951, in run
    abort(retcode)
  File "/persistent2/tsm-setup/mx/mx.py", line 3978, in abort
    traceback.print_stack()
```

**Comment by mtorp** [comment]
Hi @thepalbi 
Thank you for trying out the project.
It does indeed look like the error you are facing is related to Nodeprof or Graal. Could you maybe try with a version of Nodeprof from around January last year when this repository was created? I

**Comment by thepalbi** [comment]
Hi @mtorp ! Thanks for responding so quickly.
Tried your suggestion. I downgraded my nodeprof.js version to commit ([53b5bfa22fd80c9676056abb4113af44e455d781](https://github.com/Haiyang-Sun/nodeprof.js/commit/53b5bfa22fd80c9676056abb4113af44e455d781)), and ran the following:

1. Same TASER run above with an empty mocha test:
```
Marked sink readFileSync
Marked sink RegExp
Marked sink match
Marked sink search
Successfully loaded policy: /persistent2/tsm-setup//taser/src/DefaultPolicy.js
Successfully setup the analysis
java.lang.AssertionError: index.js(line 48):sniffFlagsclass com.oracle.truffle.js.nodes.binary.JSOrNode$NotUndefinedOrNode 1 < 2
	at ch.usi.inf.nodeprof.handlers.BaseEventHandlerNode.isLastIndex(BaseEventHandlerNode.java:216)
	at ch.usi.inf.nodeprof.analysis.ProfilerExecutionEventNode.onEnter(ProfilerExecutionEventNode.java:95)
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventProviderChainNode.innerOnEnter(ProbeNode.java:1372)
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onEnter(ProbeNode.java:887)
	at com.oracle.truffle.api.instrumentation.ProbeNode.onEnter(ProbeNode.java:157)
[...]
at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
Caused by: Attached Guest Language Frames (77)
[exit code: 1]
  File "/home/pbalbi/repos/mx/mx.py", line 17030, in <module>
    main()
  File "/home/pbalbi/repos/mx/mx.py", line 17011, in main
    retcode = c(command_args)
  File "/home/pbalbi/repos/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/mx.nodeprof/mx_nodeprof.py", line 215, in runJalangi
    _runJalangi(jalangiArgs, outFile=outFile, svm=parsed.svm, debug=parsed.debug, trace=(tracable and parsed.trace));
  File "/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/mx.nodeprof/mx_nodeprof.py", line 60, in _runJalangi
    ret = mx.run(cmdArgs, nonZeroIsFatal=True, out=out);
  File "/home/pbalbi/repos/mx/mx.py", line 12670, in run
    abort(retcode)
  File "/home/pbalbi/repos/mx/mx.py", line 3876, in abort
    traceback.print_stack()
```

2. Same Jalangi run with the empty analysis over an empty mocha test:
```
/persistent2/tsm-setup/workspace-nodeprof/graaljs/graal-nodejs/out/Release/node --jvm --vm.ea --experimental-options --engine.InstrumentExceptionsAreThrown=true --nodeprof --nodeprof.Analysis=NodeProfJalangi --nodeprof.Scope=module --nodeprof.ExcludeSource=/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/src/ch.usi.inf.nodeprof/js/analysis/trivial/emptyTemplate.js /persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/src/ch.usi.inf.nodeprof/js/jalangi.js --analysis /persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/src/ch.usi.inf.nodeprof/js/analysis/trivial/emptyTemplate.js /persistent2/tsm-setup/dynamic-js-codeql/examples/missing-requires/node_modules/mocha/bin/mocha /persistent2/tsm-setup/dynamic-js-codeql/examples/missing-requires/test
java.lang.AssertionError: index.js(line 48):sniffFlagsclass com.oracle.truffle.js.nodes.binary.JSOrNode$NotUndefinedOrNode 1 < 2
	at ch.usi.inf.nodeprof.handlers.BaseEventHandlerNode.isLastIndex(BaseEventHandlerNode.java:216)
	at ch.usi.inf.nodeprof.analysis.ProfilerExecutionEventNode.onEnter(ProfilerExecutionEventNode.java:95)
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventProviderChainNode.innerOnEnter(ProbeNode.java:1372)
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onEnter(ProbeNode.java:887)
	at com.oracle.truffle.api.instrumentation.ProbeNode.onEnter(ProbeNode.java:157)
[...]
at com.oracle.truffle.js.runtime.JSRuntime.call(JSRuntime.java:2420)
	at com.oracle.truffle.trufflenode.GraalJSAccess.functionCall(GraalJSAccess.java:1317)
	at com.oracle.truffle.trufflenode.GraalJSAccess.functionCall5(GraalJSAccess.java:1346)
Caused by: Attached Guest Language Frames (65)
[exit code: 1]
  File "/home/pbalbi/repos/mx/mx.py", line 17030, in <module>
    main()
  File "/home/pbalbi/repos/mx/mx.py", line 17011, in main
    retcode = c(command_args)
  File "/home/pbalbi/repos/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/mx.nodeprof/mx_nodeprof.py", line 215, in runJalangi
    _runJalangi(jalangiArgs, outFile=outFile, svm=parsed.svm, debug=parsed.debug, trace=(tracable and parsed.trace));
  File "/persistent2/tsm-setup/workspace-nodeprof/nodeprof.js/mx.nodeprof/mx_nodeprof.py", line 60, in _runJalangi
    ret = mx.run(cmdArgs, nonZeroIsFatal=True, out=out);
  File "/home/pbalbi/repos/mx/mx.py", line 12670, in run
    abort(retcode)
  File "/home/pbalbi/repos/mx/mx.py", line 3876, in abort
    traceback.print_stack()
```

Couple of questions to see how to move on:
1. At the moment you were working on TASER, were you able to run it alongside with mocha test suites?
2. By any chance you have the exact commit of nodeprof.js you were using?

I'll probably open an issue on the nodeprof.js repo also, maybe they can help me track down what's going on here.

**Comment by mtorp** [comment]
> At the moment you were working on TASER, were you able to run it alongside with mocha test suites?

Yes, with mocha, jest, and tap

> By any chance you have the exact commit of nodeprof.js you were using?

No, unfortunately not. I've upgraded NodeProf on the experiments machine since I used it for another research project.

What version of mocha are you using? I think we used version 5 for the experiments.

Sorry for the short answers. I'm really busy this week, but I should have more time to help next week.

**Comment by thepalbi** [comment]
Yep, you are right. Downgraded to moche 5.2.0, and it worked. I tried upgrading to the next major (6.2.2), and it fails with the same:
```
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 12
```
error. I'll create an issue in the NodeProf.js repo to check if they have some insight on what's happening.

**Comment by mtorp** [comment]
Sounds good. I'm glad you found the issue.
